desktops interactive
radishevskyi/admin-panel pull request #4
Opened 2024-08-13 18:41 UTC by radishevskyi

2024-08-16 00:22 UTC, GarantInc requested changes

2024-08-16 00:22 UTC, GarantInc commented on src/desktops/basic/reusable-table.jsx
> +          <tr className='table-row' key={rowIndex}>
Ніколи не використовуй індекс як ключ бо вони дублюються. 
Заміни на унікальні значення.
https://www.youtube.com/watch?v=OtAlPwW8DNU

2024-08-16 00:22 UTC, GarantInc commented on src/shared/constants/sidebar.data.js
>    faListAlt,
Краще буде перенести цей фал в папку sidebar.
Папка constants в основному використовується для не змінних речей.

2024-08-16 00:22 UTC, GarantInc commented on src/shared/context/context.js
> +import Basic from '@/desktops/basic/basic';
Цей контекст створений для обробки робочих столів. Тому буде правильно переназвати цей файл на desktop.js

2024-08-16 00:24 UTC, p-osypov requested changes

2024-08-16 00:24 UTC, p-osypov commented on src/desktops/basic/reusable-table.jsx
> +          <tr className='table-row' key={rowIndex}>
Ніколи не використовуй індекс як ключ бо вони дублюються.
Заміни на унікальні значення.
https://www.youtube.com/watch?v=OtAlPwW8DNU

2024-08-16 00:24 UTC, p-osypov commented on src/shared/constants/sidebar.data.js
>    faListAlt,
Краще буде перенести цей фал в папку sidebar.
Папка constants в основному використовується для не змінних речей.

2024-08-16 00:24 UTC, p-osypov commented on src/shared/context/context.js
> +import Basic from '@/desktops/basic/basic';
Цей контекст створений для обробки робочих столів. Тому буде правильно переназвати цей файл на `desktop.js`

2024-08-18 20:52 UTC, p-osypov approved these changes

2024-08-18 21:54 UTC, merged